### ISSUE TITLE
Playable scenario?

### ISSUE THREAD

**Issue by vidimus** [andrex47/MOM2-OResgateSombrio#1]
Hello, I read about this scenario and I would like to know if it's suitable for playing (bugs fixed, basically). I'm curious about it but I don't know if it's playable or not.

**Comment by vidimus** [comment]
@andrex47 Any information about this scenario?

**Comment by andrex47** [comment]
i asked the author if I could upload this scenario here, if it remained untouched it is not playable

**Comment by vidimus** [comment]
Oh, a pity in that case. Thanks for answering!
